- name: Vault Helm Chart Installation
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
  vars_files:
    - defaults/main.yaml
  tasks:
    - name: Install Vault Helm chart, initialize Vault, and unseal Vault
      ansible.builtin.include_tasks: "tasks/main.yaml"
